from .input_processor import InputProcessor
from .output_processor import OutputProcessor
from .code2vec_metric_output_processor import Code2VecMetricOutputProcessor
from .code2seq_metric_output_processor import Code2SeqMetricOutputProcessor
